/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Return a static liveness payload.
         *
         *     Returns:
         *         A :class:`HealthResponse` indicating the service is up. Does not check
         *         downstream dependencies on purpose — readiness checks belong in a
         *         separate endpoint that we will add when wiring Firestore.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe (pings Firestore)
         * @description Return readiness state, including a live Firestore ping.
         *
         *     Args:
         *         response: Injected so we can flip the status code to 503 when the
         *             downstream check fails without raising.
         *         settings: Process settings (project ID, optional emulator host).
         *
         *     Returns:
         *         :class:`ReadinessResponse` describing the outcome. The HTTP status is
         *         200 when ready, 503 otherwise.
         */
        get: operations["get_ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's contacts (paginated)
         * @description Return one page of the authenticated user's contacts.
         *
         *     Two modes:
         *
         *     - ``upcoming_in_days`` set → birthday filter applied in Python over
         *       the full set (the existing behaviour from #31). Sorted by
         *       ``(days_until_birthday, id)``. ``q`` is ignored in this mode.
         *     - ``upcoming_in_days`` unset → server-side paged query through the
         *       repository, sorted by ``(full_name_lower, id)`` and optionally
         *       narrowed by ``q`` (prefix match across name / preferred name /
         *       email).
         *
         *     Args:
         *         repo: Injected :class:`ContactRepository`.
         *         identity: Authenticated caller — scopes the listing to their data.
         *         upcoming_in_days: Optional birthday-window filter.
         *         limit: Page size; defaults to 10, capped at 100.
         *         cursor: Opaque cursor returned by a previous request.
         *         q: Optional prefix search; ignored when ``upcoming_in_days`` is set.
         *
         *     Returns:
         *         A :class:`ContactsPage` with items, ``next_cursor``, and ``total``.
         *
         *     Raises:
         *         APIError: 400 when ``cursor`` does not refer to any item in the
         *             current filtered set — the client likely raced a delete or
         *             sent a stale URL; treat this as a recoverable error and reset
         *             paging.
         */
        get: operations["list_contacts_contacts_get"];
        put?: never;
        /**
         * Create a new contact
         * @description Persist a new contact owned by the authenticated user.
         *
         *     Args:
         *         body: Contact creation payload (must not include ``owner_id``).
         *         repo: Injected :class:`ContactRepository`.
         *         identity: Authenticated caller — assigned as the contact's owner.
         *
         *     Returns:
         *         The newly created :class:`ContactResponse`.
         *
         *     Raises:
         *         APIError: 422 if the body is invalid (handled by FastAPI before this
         *             function is called).
         */
        post: operations["create_contact_contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a single contact
         * @description Return the contact with the given ID if owned by the caller.
         *
         *     Args:
         *         contact_id: UUID of the contact to fetch.
         *         repo: Injected :class:`ContactRepository`.
         *         identity: Authenticated caller.
         *
         *     Returns:
         *         The :class:`ContactResponse` for the matching contact.
         *
         *     Raises:
         *         APIError: 404 if no contact with ``contact_id`` exists *for this
         *             owner* — a wrong-owner mismatch is indistinguishable from
         *             absence on purpose, so callers cannot probe for cross-tenant
         *             existence.
         */
        get: operations["get_contact_contacts__contact_id__get"];
        /**
         * Update a contact
         * @description Apply a partial update to one of the caller's contacts.
         *
         *     Only fields explicitly included in ``body`` are changed; omitted fields
         *     retain their current values. ``owner_id`` cannot be modified.
         *
         *     Args:
         *         contact_id: UUID of the contact to update.
         *         body: Partial update payload.
         *         repo: Injected :class:`ContactRepository`.
         *         identity: Authenticated caller — must own the contact.
         *
         *     Returns:
         *         The updated :class:`ContactResponse`.
         *
         *     Raises:
         *         APIError: 404 if no contact with ``contact_id`` is owned by the caller.
         */
        put: operations["update_contact_contacts__contact_id__put"];
        post?: never;
        /**
         * Delete a contact
         * @description Remove one of the caller's contacts permanently.
         *
         *     Args:
         *         contact_id: UUID of the contact to delete.
         *         repo: Injected :class:`ContactRepository`.
         *         identity: Authenticated caller.
         *
         *     Raises:
         *         APIError: 404 if no contact with ``contact_id`` is owned by the caller.
         */
        delete: operations["delete_contact_contacts__contact_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collection-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a new collection request
         * @description Mint a signed form token, persist the request, and optionally deliver it.
         *
         *     Args:
         *         body: ``contact_id``, ``channel``, ``destination``, plus the
         *             optional ``send`` flag.
         *         service: Injected :class:`CollectionRequestService`.
         *         requests: Injected :class:`CollectionRequestRepository` — used to
         *             roll back the persisted request if the notifier fails so we
         *             never leave a request the contact never received.
         *         contacts: Injected :class:`ContactRepository` — used by the
         *             ``send=true`` path to look up the contact's first name for
         *             the email greeting.
         *         sms: Configured :class:`SmsNotifier`, or ``None`` when the
         *             Twilio settings are unset on the running service.
         *         email: Configured :class:`EmailNotifier`, or ``None`` when the
         *             Gmail settings are unset on the running service.
         *         settings: Injected :class:`Settings` — used to build the
         *             "Sign up here" URL out of ``public_base_url``.
         *         identity: Authenticated caller — must own the referenced contact.
         *             ``identity.display_name`` is the source for the owner's
         *             first name in the email subject + body.
         *
         *     Returns:
         *         :class:`IssuedRequestResponse` with the form URL and a ``sent``
         *         flag indicating whether the notifier handoff succeeded.
         *
         *     Raises:
         *         APIError: 404 if the contact isn't owned by the caller; 503
         *             when ``send=true`` but the matching notifier isn't
         *             configured on this deployment; 502 when the notifier was
         *             invoked but the upstream provider rejected the send (the
         *             persisted request is rolled back so a retry can re-mint a
         *             fresh token).
         */
        post: operations["issue_collection_request_collection_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/form/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch metadata for a self-serve form
         * @description Return enough info for the frontend to render the form.
         *
         *     Args:
         *         token: Raw signed token from the URL path.
         *         service: Injected :class:`CollectionRequestService`.
         *         limiter: Injected per-token rate limiter.
         *
         *     Returns:
         *         :class:`FormMetadataResponse` describing the form for this token.
         *
         *     Raises:
         *         APIError: 404 if the token is invalid, 410 if expired/used, 429 if
         *             rate-limited.
         */
        get: operations["get_form_metadata_form__token__get"];
        put?: never;
        /**
         * Submit the self-serve form
         * @description Persist the contact's submission and mark the request fulfilled.
         *
         *     Args:
         *         token: Raw signed token from the URL path.
         *         body: Validated submission payload.
         *         service: Injected :class:`CollectionRequestService`.
         *         limiter: Injected per-token rate limiter.
         *
         *     Raises:
         *         APIError: 404 if token/contact missing, 410 if expired/used, 429
         *             if rate-limited.
         */
        post: operations["submit_form_form__token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/digest/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List one owner's upcoming birthdays (admin debug)
         * @description Return the upcoming birthdays for a specific owner.
         *
         *     Intended for debugging and Cloud Scheduler health-check probes.
         *     Protected by OIDC validation when configured; otherwise wide-open in
         *     development.
         *
         *     Args:
         *         _auth: Resolved OIDC auth dependency (side-effect only).
         *         repo: Injected contact repository.
         *         owner_id: Firebase ``uid`` whose contacts to load.
         *         days: Look-ahead window.
         *
         *     Returns:
         *         Sorted list of upcoming birthdays for the requested owner.
         */
        get: operations["get_upcoming_birthdays_internal_digest_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/digest/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send the daily digest email to every user
         * @description Iterate every user profile and send each their own daily digest.
         *
         *     Cloud Scheduler should call this endpoint once per morning. Each user
         *     receives a digest of their own contacts at their own preferred email.
         *     A failure for one user (e.g. Gmail API error) is logged and skipped
         *     so the rest of the fan-out still completes.
         *
         *     Args:
         *         _auth: Resolved OIDC auth dependency.
         *         contacts: Contact repository (used per-owner).
         *         users: User repository — iterated to find every owner.
         *         settings: Process settings (Gmail OAuth paths, from-address).
         *         days: Look-ahead window in days.
         *         today_override: Inject a fixed date for deterministic testing.
         *
         *     Returns:
         *         :class:`DigestSendResponse` summarising the fan-out outcome.
         */
        post: operations["send_digest_internal_digest_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get (or create) the caller's profile
         * @description Return the caller's profile, creating it on first sign-in.
         *
         *     Args:
         *         repo: Injected :class:`UserRepository`.
         *         identity: Authenticated caller — supplies the ``uid`` and verified
         *             email.
         *
         *     Returns:
         *         The :class:`UserProfileResponse` for the caller's profile.
         */
        get: operations["get_or_create_profile_me_get"];
        /**
         * Update the caller's profile
         * @description Apply a partial update to the caller's profile.
         *
         *     Args:
         *         body: Partial update — only fields explicitly provided are applied.
         *         repo: Injected :class:`UserRepository`.
         *         identity: Authenticated caller.
         *
         *     Returns:
         *         The updated :class:`UserProfileResponse`.
         */
        put: operations["update_profile_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Address
         * @description A postal address.
         *
         *     Validation is intentionally permissive — we accept addresses from any
         *     country and do not normalize or geocode. The only hard requirements are a
         *     non-empty first street line and a city; everything else is optional because
         *     contacts will fill this in via a self-serve form and we do not want to
         *     block them on, for example, an unfamiliar postal-code format.
         *
         *     Attributes:
         *         street1: First line of the street address (e.g. ``"123 Main St"``).
         *         street2: Optional second line (apartment, suite, etc.).
         *         city: City or locality name.
         *         region: State, province, or region. Optional because some countries
         *             (e.g. Singapore) do not use one.
         *         postal_code: ZIP / postcode. Optional for the same reason.
         *         country: ISO 3166-1 alpha-2 country code, uppercased. Defaults to
         *             ``"US"`` since this is a personal-use app.
         */
        Address: {
            /** Street1 */
            street1: string;
            /** Street2 */
            street2?: string | null;
            /** City */
            city: string;
            /** Region */
            region?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /**
             * Country
             * @default US
             */
            country: string;
        };
        /**
         * Birthday
         * @description Month, day, and optional year of a person's birthday.
         *
         *     Attributes:
         *         month: Calendar month, 1 (January) through 12 (December).
         *         day: Day of the month, 1 through 31. Validated against ``month``
         *             (and ``year`` when present) so impossible dates are rejected.
         *         year: Four-digit Gregorian year, or ``None`` if unknown / withheld.
         *             Constrained to a sensible human range (1900–current year).
         */
        Birthday: {
            /** Month */
            month: number;
            /** Day */
            day: number;
            /** Year */
            year?: number | null;
        };
        /**
         * Channel
         * @description Channel used to deliver a collection request to a contact.
         * @enum {string}
         */
        Channel: "sms" | "email";
        /**
         * ContactResponse
         * @description Wire representation of a :class:`~birthday_tracker.models.Contact`.
         *
         *     Matches the :class:`Contact` fields but uses ``str`` for UUID/datetime
         *     so JSON serialization is explicit and stable across Python versions.
         *     The ``owner_id`` is intentionally not exposed on the wire — callers
         *     only ever see their own contacts so it carries no useful information.
         */
        ContactResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Preferred Name */
            preferred_name: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            address: components["schemas"]["Address"] | null;
            birthday: components["schemas"]["Birthday"] | null;
            /**
             * Created At
             * @description ISO-8601 UTC creation timestamp.
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO-8601 UTC last-updated timestamp.
             */
            updated_at: string;
            /**
             * Days Until Birthday
             * @description Days until the next occurrence of the contact's birthday, or null.
             */
            days_until_birthday?: number | null;
        };
        /**
         * ContactsPage
         * @description Paginated envelope for ``GET /contacts``.
         *
         *     Attributes:
         *         items: The contacts in the current page, in the route's sort order.
         *         next_cursor: Opaque cursor for the next page (the last item's UUID
         *             as a string), or ``None`` when no more pages remain.
         *         total: Total number of contacts matching the current filter — the
         *             full count, not the page length. Used by the UI for
         *             ``Page X of Y`` displays.
         */
        ContactsPage: {
            /** Items */
            items: components["schemas"]["ContactResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /**
         * CreateContactBody
         * @description Request body for ``POST /contacts``.
         *
         *     Note that ``owner_id`` is intentionally not a field — it is set
         *     server-side from the authenticated identity so callers cannot
         *     impersonate other users by spoofing it.
         */
        CreateContactBody: {
            /**
             * Full Name
             * @description Full name.
             */
            full_name: string;
            /**
             * Preferred Name
             * @description Nickname used in greetings.
             */
            preferred_name?: string | null;
            /**
             * Email
             * @description Email address.
             */
            email?: string | null;
            /**
             * Phone
             * @description Phone number (E.164).
             */
            phone?: string | null;
            /** @description Postal address. */
            address?: components["schemas"]["Address"] | null;
            /** @description Birthday. */
            birthday?: components["schemas"]["Birthday"] | null;
        };
        /**
         * DigestSendResponse
         * @description Response body for ``POST /internal/digest/send``.
         *
         *     Attributes:
         *         date: The calendar date used as reference (ISO 8601).
         *         users: Per-user outcome — one entry per known profile.
         *         delivered: Total emails actually sent across all users.
         *         skipped: Users who would have received a digest but the
         *             per-process idempotency guard suppressed it.
         *         failed: Users whose delivery raised an exception (continued).
         */
        DigestSendResponse: {
            /** Date */
            date: string;
            /** Users */
            users: components["schemas"]["DigestUserResult"][];
            /** Delivered */
            delivered: number;
            /** Skipped */
            skipped: number;
            /** Failed */
            failed: number;
        };
        /**
         * DigestUpcomingResponse
         * @description Response body for ``GET /internal/digest/upcoming``.
         *
         *     Attributes:
         *         owner_id: Owner whose upcoming birthdays are listed.
         *         days: The look-ahead window used.
         *         count: Number of upcoming birthdays found.
         *         items: The list of upcoming birthdays sorted by days_until.
         */
        DigestUpcomingResponse: {
            /** Owner Id */
            owner_id: string;
            /** Days */
            days: number;
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["UpcomingBirthdayResponse"][];
        };
        /**
         * DigestUserResult
         * @description Per-user outcome inside :class:`DigestSendResponse`.
         *
         *     Attributes:
         *         owner_id: Firebase ``uid`` of the user this entry describes.
         *         owner_email: Address the digest was (or would be) sent to.
         *         sent: Whether an email was actually delivered.
         *         count: Number of upcoming birthdays in the digest.
         *         error: Failure message if delivery raised. ``None`` on success.
         */
        DigestUserResult: {
            /** Owner Id */
            owner_id: string;
            /** Owner Email */
            owner_email: string;
            /** Sent */
            sent: boolean;
            /** Count */
            count: number;
            /** Error */
            error?: string | null;
        };
        /**
         * FormMetadataResponse
         * @description Returned by ``GET /form/{token}``.
         *
         *     Attributes:
         *         greeting_name: First-name-style label safe to show in the form
         *             header. We never expose contact secrets via the public form.
         *         channel: Channel used to deliver the link.
         *         expires_at: ISO-8601 expiry timestamp.
         */
        FormMetadataResponse: {
            /** Greeting Name */
            greeting_name: string;
            /** Channel */
            channel: string;
            /** Expires At */
            expires_at: string;
        };
        /**
         * FormSubmissionBody
         * @description Validated payload accepted by ``POST /form/{token}``.
         */
        FormSubmissionBody: {
            /** Full Name */
            full_name: string;
            /** Preferred Name */
            preferred_name?: string | null;
            address: components["schemas"]["Address"];
            birthday: components["schemas"]["Birthday"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Payload returned by :func:`get_health`.
         *
         *     Attributes:
         *         status: Always ``"ok"`` when the process can serve a response.
         *         version: Package version string for the running build.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * IssueRequestBody
         * @description Request body for ``POST /collection-requests``.
         */
        IssueRequestBody: {
            /**
             * Contact Id
             * Format: uuid
             * @description ID of the contact this request is for.
             */
            contact_id: string;
            /** @description Delivery channel for the form link. */
            channel: components["schemas"]["Channel"];
            /**
             * Destination
             * @description Phone number (E.164) or email address the link will be sent to.
             */
            destination: string;
            /**
             * Send
             * @description When true, the backend delivers the link via the matching notifier (Twilio for ``sms``, Gmail for ``email``) and only returns success once the provider acknowledges the send. When false (default), the backend just mints the link and returns the URL for the owner to deliver manually.
             * @default false
             */
            send: boolean;
        };
        /**
         * IssuedRequestResponse
         * @description Response body returned by ``POST /collection-requests``.
         */
        IssuedRequestResponse: {
            /**
             * Request Id
             * Format: uuid
             * @description ID of the persisted CollectionRequest.
             */
            request_id: string;
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            channel: components["schemas"]["Channel"];
            /** Destination */
            destination: string;
            /**
             * Expires At
             * @description ISO-8601 expiry timestamp.
             */
            expires_at: string;
            /**
             * Form Url
             * @description Public URL to send to the contact.
             */
            form_url: string;
            /**
             * Sent
             * @description True when the backend successfully handed the link off to the configured notifier; false when ``send`` was not requested.
             */
            sent: boolean;
        };
        /**
         * ReadinessResponse
         * @description Payload returned by :func:`get_ready`.
         *
         *     Attributes:
         *         status: ``"ready"`` on success, ``"not_ready"`` on failure.
         *         firestore: ``"ok"`` or a short failure description.
         */
        ReadinessResponse: {
            /** Status */
            status: string;
            /** Firestore */
            firestore: string;
        };
        /**
         * UpcomingBirthdayResponse
         * @description Wire representation of :class:`~birthday_tracker.services.digest.UpcomingBirthday`.
         *
         *     Attributes:
         *         contact_id: UUID string of the contact.
         *         full_name: Contact's full legal name.
         *         preferred_name: Nickname, if set.
         *         days_until: Days until the next birthday occurrence (0 = today).
         */
        UpcomingBirthdayResponse: {
            /** Contact Id */
            contact_id: string;
            /** Full Name */
            full_name: string;
            /** Preferred Name */
            preferred_name: string | null;
            /** Days Until */
            days_until: number;
        };
        /**
         * UpdateContactBody
         * @description Request body for ``PUT /contacts/{contact_id}``.
         *
         *     All fields are optional; only supplied fields are applied.
         */
        UpdateContactBody: {
            /** Full Name */
            full_name?: string | null;
            /** Preferred Name */
            preferred_name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            address?: components["schemas"]["Address"] | null;
            birthday?: components["schemas"]["Birthday"] | null;
        };
        /**
         * UpdateProfileBody
         * @description Request body for ``PUT /me`` — both fields optional.
         */
        UpdateProfileBody: {
            /**
             * Digest Owner Email
             * @description Where the daily digest should be delivered. Defaults to the sign-in email.
             */
            digest_owner_email?: string | null;
            /**
             * Digest Timezone
             * @description IANA timezone name used for digest date math.
             */
            digest_timezone?: string | null;
        };
        /**
         * UserProfileResponse
         * @description Wire representation of :class:`~birthday_tracker.models.User`.
         *
         *     Identity-derived fields (``first_name``, ``last_name``, ``phone``)
         *     come straight from the verified Firebase token on every request —
         *     they are not persisted in the User document, so editing them is a
         *     Firebase / Google account concern, not an app concern. Persisted
         *     fields (``digest_*``) live on the User row and can be updated via
         *     ``PUT /me``.
         */
        UserProfileResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /**
             * First Name
             * @description Owner's first name, derived from the Firebase display name.
             */
            first_name: string | null;
            /**
             * Last Name
             * @description Owner's last name (joined remainder of the display name).
             */
            last_name: string | null;
            /**
             * Phone
             * @description Phone number from the Firebase token, or ``None`` when unset.
             */
            phone: string | null;
            /** Digest Owner Email */
            digest_owner_email: string | null;
            /** Digest Timezone */
            digest_timezone: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Firestore unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_contacts_contacts_get: {
        parameters: {
            query?: {
                /** @description When set, return only contacts whose birthday falls within the next *N* days (inclusive). Contacts without a birthday are excluded. */
                upcoming_in_days?: number | null;
                /** @description Maximum number of items to return in this page. */
                limit?: number;
                /** @description Opaque pagination cursor — the ``id`` of the last item from the previous page. Items strictly after that position in the route's sort order are returned. */
                cursor?: string | null;
                /** @description Case-insensitive prefix search across full name, preferred name, and email. Whitespace-only values are treated as no filter. Ignored when ``upcoming_in_days`` is set. */
                q?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contact_contacts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contact_contacts__contact_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contact_contacts__contact_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContactBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contact_contacts__contact_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_collection_request_collection_requests_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_form_metadata_form__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormMetadataResponse"];
                };
            };
            /** @description Token unknown or malformed */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token expired or request already fulfilled */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded for this token */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submit_form_form__token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormSubmissionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token unknown or contact missing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token expired or request already fulfilled */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded for this token */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_upcoming_birthdays_internal_digest_upcoming_get: {
        parameters: {
            query: {
                /** @description Firebase uid of the user to inspect. */
                owner_id: string;
                /** @description Look-ahead window in days (inclusive). */
                days?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestUpcomingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_digest_internal_digest_send_post: {
        parameters: {
            query?: {
                /** @description Look-ahead window in days (inclusive). */
                days?: number;
                /** @description Override today's date (ISO 8601). Test use only. */
                today?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestSendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_or_create_profile_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_me_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
