/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Return a static liveness payload.
         *
         *     Returns:
         *         A :class:`HealthResponse` indicating the service is up. Does not check
         *         downstream dependencies on purpose — readiness checks belong in a
         *         separate endpoint that we will add when wiring Firestore.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe (pings Firestore)
         * @description Return readiness state, including a live Firestore ping.
         *
         *     Args:
         *         response: Injected so we can flip the status code to 503 when the
         *             downstream check fails without raising.
         *         settings: Process settings (project ID, optional emulator host).
         *
         *     Returns:
         *         :class:`ReadinessResponse` describing the outcome. The HTTP status is
         *         200 when ready, 503 otherwise.
         */
        get: operations["get_ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all contacts (owner only)
         * @description Return all contacts, optionally filtered to upcoming birthdays.
         *
         *     Args:
         *         repo: Injected :class:`ContactRepository`.
         *         _owner: Authenticated owner identity (stub).
         *         upcoming_in_days: Optional filter: only contacts with a birthday
         *             within the next ``upcoming_in_days`` calendar days are returned.
         *             Contacts without a birthday are omitted when this filter is active.
         *
         *     Returns:
         *         List of :class:`ContactResponse` objects, ordered by
         *         ``days_until_birthday`` when ``upcoming_in_days`` is set, otherwise
         *         by ascending ``full_name``.
         */
        get: operations["list_contacts_contacts_get"];
        put?: never;
        /**
         * Create a new contact (owner only)
         * @description Persist a new contact and return the saved record.
         *
         *     Args:
         *         body: Contact creation payload.
         *         repo: Injected :class:`ContactRepository`.
         *         _owner: Authenticated owner identity (stub).
         *
         *     Returns:
         *         The newly created :class:`ContactResponse`.
         *
         *     Raises:
         *         APIError: 422 if the body is invalid (handled by FastAPI before this
         *             function is called).
         */
        post: operations["create_contact_contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a single contact (owner only)
         * @description Return the contact with the given ID.
         *
         *     Args:
         *         contact_id: UUID of the contact to fetch.
         *         repo: Injected :class:`ContactRepository`.
         *         _owner: Authenticated owner identity (stub).
         *
         *     Returns:
         *         The :class:`ContactResponse` for the matching contact.
         *
         *     Raises:
         *         APIError: 404 if no contact with ``contact_id`` exists.
         */
        get: operations["get_contact_contacts__contact_id__get"];
        /**
         * Update a contact (owner only)
         * @description Apply a partial update to an existing contact.
         *
         *     Only fields explicitly included in ``body`` are changed; omitted fields
         *     retain their current values.
         *
         *     Args:
         *         contact_id: UUID of the contact to update.
         *         body: Partial update payload.
         *         repo: Injected :class:`ContactRepository`.
         *         _owner: Authenticated owner identity (stub).
         *
         *     Returns:
         *         The updated :class:`ContactResponse`.
         *
         *     Raises:
         *         APIError: 404 if no contact with ``contact_id`` exists.
         */
        put: operations["update_contact_contacts__contact_id__put"];
        post?: never;
        /**
         * Delete a contact (owner only)
         * @description Remove a contact permanently.
         *
         *     Args:
         *         contact_id: UUID of the contact to delete.
         *         repo: Injected :class:`ContactRepository`.
         *         _owner: Authenticated owner identity (stub).
         *
         *     Raises:
         *         APIError: 404 if no contact with ``contact_id`` exists.
         */
        delete: operations["delete_contact_contacts__contact_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collection-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a new collection request (owner only)
         * @description Mint a token and persist a pending collection request.
         *
         *     Args:
         *         body: Request payload with ``contact_id``, ``channel``, ``destination``.
         *         service: Injected :class:`CollectionRequestService`.
         *         _owner: Authenticated owner identity (stub — real auth in issue #7).
         *
         *     Returns:
         *         :class:`IssuedRequestResponse` carrying the public form URL.
         *
         *     Raises:
         *         APIError: 404 if the referenced contact does not exist.
         */
        post: operations["issue_collection_request_collection_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/form/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch metadata for a self-serve form
         * @description Return enough info for the frontend to render the form.
         *
         *     Args:
         *         token: Raw signed token from the URL path.
         *         service: Injected :class:`CollectionRequestService`.
         *         limiter: Injected per-token rate limiter.
         *
         *     Returns:
         *         :class:`FormMetadataResponse` describing the form for this token.
         *
         *     Raises:
         *         APIError: 404 if the token is invalid, 410 if expired/used, 429 if
         *             rate-limited.
         */
        get: operations["get_form_metadata_form__token__get"];
        put?: never;
        /**
         * Submit the self-serve form
         * @description Persist the contact's submission and mark the request fulfilled.
         *
         *     Args:
         *         token: Raw signed token from the URL path.
         *         body: Validated submission payload.
         *         service: Injected :class:`CollectionRequestService`.
         *         limiter: Injected per-token rate limiter.
         *
         *     Raises:
         *         APIError: 404 if token/contact missing, 410 if expired/used, 429
         *             if rate-limited.
         */
        post: operations["submit_form_form__token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Address
         * @description A postal address.
         *
         *     Validation is intentionally permissive — we accept addresses from any
         *     country and do not normalize or geocode. The only hard requirements are a
         *     non-empty first street line and a city; everything else is optional because
         *     contacts will fill this in via a self-serve form and we do not want to
         *     block them on, for example, an unfamiliar postal-code format.
         *
         *     Attributes:
         *         street1: First line of the street address (e.g. ``"123 Main St"``).
         *         street2: Optional second line (apartment, suite, etc.).
         *         city: City or locality name.
         *         region: State, province, or region. Optional because some countries
         *             (e.g. Singapore) do not use one.
         *         postal_code: ZIP / postcode. Optional for the same reason.
         *         country: ISO 3166-1 alpha-2 country code, uppercased. Defaults to
         *             ``"US"`` since this is a personal-use app.
         */
        Address: {
            /** Street1 */
            street1: string;
            /** Street2 */
            street2?: string | null;
            /** City */
            city: string;
            /** Region */
            region?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /**
             * Country
             * @default US
             */
            country: string;
        };
        /**
         * Birthday
         * @description Month, day, and optional year of a person's birthday.
         *
         *     Attributes:
         *         month: Calendar month, 1 (January) through 12 (December).
         *         day: Day of the month, 1 through 31. Validated against ``month``
         *             (and ``year`` when present) so impossible dates are rejected.
         *         year: Four-digit Gregorian year, or ``None`` if unknown / withheld.
         *             Constrained to a sensible human range (1900–current year).
         */
        Birthday: {
            /** Month */
            month: number;
            /** Day */
            day: number;
            /** Year */
            year?: number | null;
        };
        /**
         * Channel
         * @description Channel used to deliver a collection request to a contact.
         * @enum {string}
         */
        Channel: "sms" | "email";
        /**
         * ContactResponse
         * @description Wire representation of a :class:`~birthday_tracker.models.Contact`.
         *
         *     Matches the :class:`Contact` fields but uses ``str`` for UUID/datetime
         *     so JSON serialization is explicit and stable across Python versions.
         */
        ContactResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Preferred Name */
            preferred_name: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            address: components["schemas"]["Address"] | null;
            birthday: components["schemas"]["Birthday"] | null;
            /**
             * Created At
             * @description ISO-8601 UTC creation timestamp.
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO-8601 UTC last-updated timestamp.
             */
            updated_at: string;
            /**
             * Days Until Birthday
             * @description Days until the next occurrence of the contact's birthday, or null.
             */
            days_until_birthday?: number | null;
        };
        /**
         * CreateContactBody
         * @description Request body for ``POST /contacts``.
         */
        CreateContactBody: {
            /**
             * Full Name
             * @description Full name.
             */
            full_name: string;
            /**
             * Preferred Name
             * @description Nickname used in greetings.
             */
            preferred_name?: string | null;
            /**
             * Email
             * @description Email address.
             */
            email?: string | null;
            /**
             * Phone
             * @description Phone number (E.164).
             */
            phone?: string | null;
            /** @description Postal address. */
            address?: components["schemas"]["Address"] | null;
            /** @description Birthday. */
            birthday?: components["schemas"]["Birthday"] | null;
        };
        /**
         * FormMetadataResponse
         * @description Returned by ``GET /form/{token}``.
         *
         *     Attributes:
         *         greeting_name: First-name-style label safe to show in the form
         *             header. We never expose contact secrets via the public form.
         *         channel: Channel used to deliver the link.
         *         expires_at: ISO-8601 expiry timestamp.
         */
        FormMetadataResponse: {
            /** Greeting Name */
            greeting_name: string;
            /** Channel */
            channel: string;
            /** Expires At */
            expires_at: string;
        };
        /**
         * FormSubmissionBody
         * @description Validated payload accepted by ``POST /form/{token}``.
         */
        FormSubmissionBody: {
            /** Full Name */
            full_name: string;
            /** Preferred Name */
            preferred_name?: string | null;
            address: components["schemas"]["Address"];
            birthday: components["schemas"]["Birthday"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Payload returned by :func:`get_health`.
         *
         *     Attributes:
         *         status: Always ``"ok"`` when the process can serve a response.
         *         version: Package version string for the running build.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * IssueRequestBody
         * @description Request body for ``POST /collection-requests``.
         */
        IssueRequestBody: {
            /**
             * Contact Id
             * Format: uuid
             * @description ID of the contact this request is for.
             */
            contact_id: string;
            /** @description Delivery channel for the form link. */
            channel: components["schemas"]["Channel"];
            /**
             * Destination
             * @description Phone number (E.164) or email address the link will be sent to.
             */
            destination: string;
        };
        /**
         * IssuedRequestResponse
         * @description Response body returned by ``POST /collection-requests``.
         */
        IssuedRequestResponse: {
            /**
             * Request Id
             * Format: uuid
             * @description ID of the persisted CollectionRequest.
             */
            request_id: string;
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            channel: components["schemas"]["Channel"];
            /** Destination */
            destination: string;
            /**
             * Expires At
             * @description ISO-8601 expiry timestamp.
             */
            expires_at: string;
            /**
             * Form Url
             * @description Public URL to send to the contact.
             */
            form_url: string;
        };
        /**
         * ReadinessResponse
         * @description Payload returned by :func:`get_ready`.
         *
         *     Attributes:
         *         status: ``"ready"`` on success, ``"not_ready"`` on failure.
         *         firestore: ``"ok"`` or a short failure description.
         */
        ReadinessResponse: {
            /** Status */
            status: string;
            /** Firestore */
            firestore: string;
        };
        /**
         * UpdateContactBody
         * @description Request body for ``PUT /contacts/{contact_id}``.
         *
         *     All fields are optional; only supplied fields are applied.
         */
        UpdateContactBody: {
            /** Full Name */
            full_name?: string | null;
            /** Preferred Name */
            preferred_name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            address?: components["schemas"]["Address"] | null;
            birthday?: components["schemas"]["Birthday"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Firestore unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_contacts_contacts_get: {
        parameters: {
            query?: {
                /** @description When set, return only contacts whose birthday falls within the next *N* days (inclusive). Contacts without a birthday are excluded. */
                upcoming_in_days?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contact_contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contact_contacts__contact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contact_contacts__contact_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContactBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contact_contacts__contact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_collection_request_collection_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_form_metadata_form__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormMetadataResponse"];
                };
            };
            /** @description Token unknown or malformed */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token expired or request already fulfilled */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded for this token */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submit_form_form__token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormSubmissionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token unknown or contact missing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token expired or request already fulfilled */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded for this token */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
